import type { Metadata } from "next";
import "./globals.css";
import FlareCursor from "../components/FlareCursor";

export const metadata: Metadata = {
  title: "Stiveune",
  description: "Generated by my own hands",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <FlareCursor />
        {children}
      </body>
    </html>
  );
}
